<?php
return [
//    Umumiy
    'ARM information system' => 'АРМ ахборот тизими',
    'Digital library' => 'Рақамли кутубхона',
    'Read more' => 'Батафсил',
    'Search' => 'Сайтдан излаш',
    'Not found' => 'Маълумот топилмади',
    'Author' => 'Муаллиф',
    'All' => 'Барчаси',
    'Daily' => 'Кунлик',
    'News' => 'Янгиликлар',
    'Special version' => 'Махсус версия',
    'Personal cabinet' => 'Шахсий кабинет',
    'Gender' => 'Жинс',
    'Passport' => 'Пасспорт',
    'Date' => 'сана',
    'Full name' =>'Ф.И.Ш.',

//    Menyular
    'Home' => 'Бош саҳифа',
    'Menus' => 'Менюлар',
    'Support' => 'Техник қуллаб-қувватлаш',
    'Give a book' => 'Китоб бериш',
    'Give' => 'Бериш',
    'Take' => 'Қайтариш',
    'Book fund' => 'Китоб фонди',
    'Books' => 'Китоблар',
    'Book' => 'Китоб',
    'Inventory search' => 'Инвентар қидириш',
    'Kind of literature' => 'Адабиёт тури',
    'Category' => 'Категория',
    'Book status' => 'Китоб ҳолати',
    'Form' => 'Формуляр',
    'Students' => 'Талабалар',
    'Employees' => 'Ходимлар',
    'Reports' => 'Ҳисоботлар',
    'Membership' => 'Аъзолик',

    //    Pages
    'Monitoring' => 'Мониторинг',
    'The number of books in the title' => 'Номдаги китоблар сони',
    'Number of books in the library' => 'Кутубхонадаги китоблар сони',
    'Number of users' => 'Фойдаланувчилар сони',
    'Size of e-books' => 'Электрон китоблар ҳажми',
    'Size of audio books' => 'Аудио китоблар ҳажми',
    'ID' => 'Код',
    'Name' => 'Номи',
    'Publisher Name' => 'Нашриёт номи',
    'Year' => 'Йил',
    'A copy' => 'Нусхаси',
    'Price' => 'Нархи (UZS)',
    'UDK' => 'УДК',

//    Kontakt
    'Phone' => 'Телефон',
    'E-mail' => 'Электрон почта',
    'Contact' => 'Боғланиш',
    'Address' => 'Манзил',
    'Fax' => 'Факс',

//    Tizim
    'ftitle' => 'Ўшбу сайт материалларидан фойдаланилганда, ушбу ресурсга ҳавола этилиши шарт',
    'File' => 'Файл',
    'Clear' => 'Тозалаш',
    'Send' => 'Юбориш',
    'Verification code' => 'Текширув коди',
    'Error !' => 'Хатолик !',
    'Download' => 'Юклаб олиш',
    'Guest' => 'Фойдаланувчилар сони',
    'Status' => 'Ҳолати',
    'Exit' => 'Чиқиш',
    'System' => 'Тизим',
    'Login history' => 'Кириш тарихи',
    'System settings' => 'Тизим созламалари',
    'Program version' => 'Дастур версияси',
    'System indicators' => 'Тизим кўрсаткичлар',
    'Log in' => 'Тизимга кириш',
    'For employees' => 'Ходимлар учун',
    'For students' => 'Талабалар учун',
    'Enter search keyword' => 'Қидирув калит сўзини киритинг',
    'In number' => 'Сонда',
    'In the name' => 'Номдаги',
    'Catalogs' => 'Каталоглар',
    'Users' => 'Фойдаланувчилар',
    'User' => 'Фойдаланувчи',
    'Electronic' => 'Электрон',
    'Audio' => 'Аудио',
    'Using the library' => 'Кутубхонадан фойдаланиш',
    'Filter' => 'Филтр',
    'Archive' => 'Архив',

//    =====================
    'Monthly' => 'Ойлик',
    'oy1' => 'Январ',
    'oy2' => 'Феврал',
    'oy3' => 'Март',
    'oy4' => 'Апрел',
    'oy5' => 'Май',
    'oy6' => 'Июн',
    'oy7' => 'Июл',
    'oy8' => 'Август',
    'oy9' => 'Сентябр',
    'oy10' => 'Октябр',
    'oy11' => 'Ноябр',
    'oy12' => 'Декабр',
]; ?>