<?php
return [
    //    Umumiy
    'ARM information system' => 'ИC АРМ',
    'Digital library' => 'Цифровая библиотека',
    'Read more' => 'Подробнее',
    'Search' => 'Поиск',
    'Not found' => 'Не найдено',
    'Author' => 'Автор',
    'All' => 'Все',
    'Daily' => 'Ежедневно',
    'News' => 'Новости',
    'Special version' => 'Специальная версия',
    'Personal cabinet' => 'Личный кабинет',
    'Gender' => 'пол',
    'Passport' => 'Пасспорт',
    'Date' => 'дата',
    'Full name' => 'Ф.И.Ш.',

//    Menyular
    'Home' => 'Главный',
    'Menus' => 'Меню',
    'Support' => 'Техническая поддержка',
    'Give a book' => 'Дайте книгу',
    'Give' => 'Давать',
    'Take' => 'Брать',
    'Book fund' => 'Книжный фонд',
    'Books' => 'Книги',
    'Book' => 'Книга',
    'Inventory search' => 'Поиск по инвентарю',
    'Kind of literature' => 'Вид литературы',
    'Category' => 'Категория',
    'Book status' => 'Статус книги',
    'Form' => 'Формуляр',
    'Students' => 'Студенты',
    'Employees' => 'Сотрудники',
    'Reports' => 'Отчеты',
    'Membership' => 'Членство',

    //    Pages
    'Monitoring' => 'Мониторинг',
    'The number of books in the title' => 'Количество книг в названии',
    'Number of books in the library' => 'Количество книг в библиотеке',
    'Number of users' => 'Количество пользователей',
    'Size of e-books' => 'Размер электронных книг',
    'Size of audio books' => 'Размер аудиокниг',
    'ID' => 'Идентификатор',
    'Name' => 'Имя',
    'Publisher Name' => 'Имя издателя',
    'Year' => 'Год',
    'A copy' => 'Копия',
    'Price' => 'Цена (UZS)',
    'UDK' => 'УДК',

//    Kontakt
    'Phone' => 'Телефон',
    'E-mail' => 'Электронная почта',
    'Contact' => 'Контакт',
    'Address' => 'Адрес',
    'Fax' => 'Факс',

//    Tizim
    'ftitle' => 'Ўшбу сайт материалларидан фойдаланилганда, ушбу ресурсга ҳавола этилиши шарт',
    'File' => 'Файл',
    'Clear' => 'Очистить',
    'Send' => 'отправлять',
    'Verification code' => 'Проверочный код',
    'Error !' => 'Ошибка !',
    'Download' => 'скачать',
    'Guest' => 'гость',
    'Status' => 'статус',
    'Exit' => 'Выход',
    'System' => 'Система',
    'Login history' => 'История входов',
    'System settings' => 'Настройки системы',
    'Program version' => 'Версия программы',
    'System indicators' => 'Системные показатели',
    'Log in' => 'Авторизоваться',
    'For employees' => 'Для сотрудников',
    'For students' => 'Для студентов',
    'Enter search keyword' => 'Введите ключевое слово для поиска',
    'In number' => 'В количестве',
    'In the name' => 'Во имя',
    'Catalogs' => 'Каталоги',
    'Users' => 'Пользователи',
    'User' => 'Пользователи',
    'Electronic' => 'Электронный',
    'Audio' => 'Аудио',
    'Using the library' => 'Использование библиотеки',
    'Filter' => 'Фильтр',
    'Archive' => 'Архив',

//    =====================
    'Monthly' => 'Ежемесячно',
    'oy1' => 'Январ',
    'oy2' => 'Феврал',
    'oy3' => 'Март',
    'oy4' => 'Апрел',
    'oy5' => 'Май',
    'oy6' => 'Июн',
    'oy7' => 'Июл',
    'oy8' => 'Август',
    'oy9' => 'Сентябр',
    'oy10' => 'Октябр',
    'oy11' => 'Ноябр',
    'oy12' => 'Декабр',
]; ?>