<?php
return [
    //    Umumiy
    'ARM information system' => 'ARM axborot tizimi',
    'Digital library' => 'Raqamli kutubxona',
    'Read more' => 'Batafsil',
    'Search' => 'Saytdan izlash',
    'Not found' => "Ma'lumot topilmadi",
    'Author' => 'Muallif',
    'All' => 'Barchasi',
    'Daily' => 'Kunlik',
    'Menu' => 'Menyu',
    'News' => 'Yangiliklar',
    'Get to know university life and events' => 'Universitet hayoti va undagi voqealar bilan tanishing',
    'News Type' => 'Yangilik turi',
    'Special version' => 'Maxsus versiya',
    'Personal cabinet' => 'Shaxsiy kabinet',
    'Gender' => 'Jins',
    'Passport' => 'Passport',
    'Date' => 'Sana',
    'Full name' => 'F.I.Sh.',

//    Menyular
    'Home' => 'Bosh sahifa',
    'About' => 'Haqimizda',
    'Services' => 'Xizmatlar',
    'Contact' => 'Aloqa',
    'All Copyright' => 'Barcha huquqlar himoyalangan',
    'Give' => 'Berish',
    'Visiting Day' => 'Qabul kunlari',
    'Take' => 'Qaytarish',
    'Book fund' => 'Kitob fondi',
    'Books' => 'Kitoblar',
    'Book' => 'Kitob',
    'Inventory search' => 'Inventar qidirish',
    'Kind of literature' => 'Adabiyot turi',
    'Category' => 'Kategoriya',
    'Book status' => 'Kitob holati',
    'Form' => 'Formulyar',
    'Name' => 'Nomi',
    'Content' => 'Mazmuni',
    'Students' => 'Talabalar',
    'Employees' => 'Xodimlar',
    'Reports' => 'Hisobotlar',
    'Membership' => 'A\'zolik',

//    Pages
    'Monitoring' => 'Monitoring',

//    Kontakt
    'Phone' => 'Telefon',
    'Email' => 'Elektron pochta',
    'Address' => 'Manzil',
    'Location' => 'Manzil',
    'Fax' => 'Faks',
    'Make a call' => 'Qo\'ng\'iroq qiling',

    //    Ijtimoiy tarmoqlar
    'Tg Channel' => 'Telegram kanal',
    'Fb Channel' => 'Facebook kanal',
    'In Channel' => 'Linkedin kanal',
    'Tw Channel' => 'Twitter kanal',
    'Youtube Channel' => 'Youtube kanal',
    'Instagram Channel' => 'Instagram kanal',

//    Tizim
    'ftitle' => 'O`shbu sayt materiallaridan foydalanilganda, ushbu resursga havola etilishi shart',
    'File' => 'Fayl',
    'Clear' => 'Tozalash',
    'Send' => 'Yuborish',
    'Verification code' => 'Tekshiruv kodi',
    'Error !' => 'Xatolik !',
    'Download' => 'Yuklab olish',
    'Guest' => 'Foydalanuvchilar soni',
    'Status' => 'Holati',
    'Exit' => 'Chiqish',
    'System' => 'Tizim',
    'Login history' => 'Kirish tarixi',
    'System settings' => 'Tizim sozlamalari',
    'Program version' => 'Dastur versiyasi',
    'System indicators' => 'Tizim ko`rsatkichlar',
    'Log in' => 'Tizimga kirish',
    'For employees' => 'Xodimlar uchun',
    'For students' => 'Talabalar uchun',
    'Enter search keyword' => 'Qidiruv kalit so\'zini kiriting',
    'In number' => 'Sonda',
    'In the name' => 'Nomdagi',
    'Catalogs' => 'Kataloglar',
    'Users' => 'Foydalanuvchilar',
    'User' => 'Foydalanuvchi',
    'Electronic' => 'Elektron',
    'Audio' => 'Audio',
    'Using the library' => 'Kutubxonadan foydalanish',
    'Filter' => 'Filtr',
    'Loading' => 'Yuklanmoqda',
    'All right reserved' => 'Barcha huquqlar himoyalangan',

//    ====================
    'Monthly' => 'Oylik',
    'oy1' => 'Yanvar',
    'oy2' => 'Fevral',
    'oy3' => 'Mart',
    'oy4' => 'Aprel',
    'oy5' => 'May',
    'oy6' => 'Iyun',
    'oy7' => 'Iyul',
    'oy8' => 'Avgust',
    'oy9' => 'Sentyabr',
    'oy10' => 'Oktyabr',
    'oy11' => 'Noyabr',
    'oy12' => 'Dekabr',
]; ?>